### PR TITLE
feat: overhaul of website design

### PR DESCRIPTION
**Pull request by stockbal**
- replace jekyll with VuePress
- new responsive layout
- switch between light/dark theme
- integrated client side search
- breadcrumbs and sidebar for better navigation

### CODE REVIEW

**Comment by stockbal** [comment]
I am not sure about deployment process. I could only find a „build“ step in the current pipeline. 

With the overhaul the site is built and deployed on an extra branch „gh-pages“. After the first deployment to this branch, the „CNAME“ file would need to be added again

**Comment by stockbal** [comment]
Yes. From my side we are good to go😊.
The last commit was just code cosmetics.

**Comment by mbtools** [comment]
deploy finished without errors. i added CNAME to the `gh-pages`. 

however, https://docs.abapgit.org/ is giving 404

the old environment was at `github-pages`:

image

maybe it should deploy to `github-pages` branch or do you see a different issue?

**Comment by larshp** [comment]
cname added in https://github.com/abapGit/docs.abapgit.org/commit/99e770bfc7ad370f37ab32726553d391dab12e11

**Comment by mbtools** [comment]
now it's pointing to the main branch (which doesn't have index.html) 

i think the build source in repo settings is still set to "branch" but should be "github action"

**Comment by mbtools** [comment]
and we are live. yay!

image

**Pull request merged**
