### PR TITLE
update docs font to match abapgit

### PR DESCRIPTION
**Pull request by FreHu**
Before
image
After
image

### CODE REVIEW

**Comment by flaiker** [comment]
This will only work for users on desktop who have installed SAP GUI or somehow manually installed the font?

**Comment by FreHu** [comment]
i believe the fonts are specified in order of preference and the browser will try to do its best

**Comment by flaiker** [comment]
I think the license would allow for redistribution?

https://experience.sap.com/fiori-design-web/downloads/#download-font-72

**Comment by FreHu** [comment]
No, all text rendered in `72` and its intellectual property automatically belongs to SAP. But we don't pursue people for it because it would be too much work to read it all.

```
Anyone who uses open source software licensed under Apache 2.0 must include the following in their copy of the code, whether they have modified it or not:

The original copyright notice
A copy of the license itself
If applicable, a statement of any significant changes made to the original code
A copy of the NOTICE file with attribution notes (if the original library has one)
```

In all seriousness it should be fine, is there a difference between use and redistribution?

**Comment by flaiker** [comment]
I don't know. Legally seems like a minefield so I'll just withdraw my statement ;)

**Pull request merged**
