### PR TITLE
Update other-test-ssl.md

### PR DESCRIPTION
**Pull request by WegnerDan**
I've added response data to the ssl test report and also a way to display the response in CL_ABAP_BROWSER. 
Can be helpful if the response error code isn't enough to find out where things are going wrong.

### CODE REVIEW

**Comment by mbtools** [comment]
Thanks for the enhancement Daniel! Let's put the code in a separate file and link to it for easier download.

**Comment by WegnerDan** [comment]
Where is a good place for the .abap file?

**Comment by mbtools** [comment]
a new /src/ folder :-)

**Comment by WegnerDan** [comment]
I've added the report as .abap file, but I'm unsure how to link it without referencing my fork.
Can I use a relative link?

**Comment by mbtools** [comment]
Yes. Relative links are fine

**Comment by WegnerDan** [comment]
I've linked it and it seems to work fine, but the .abap file is downloaded, instead of opened in-browser.

**Review by mbtools — APPROVED** [review]
No worry. There are some limitations on how markdown links are opened on GitHub. 

LGTM

**Comment by mbtools** [comment]
Tested. Works

**Comment by WegnerDan** [comment]
The relative link to the report does not seem to work. 
image

**Comment by mbtools** [comment]
https://github.com/abapGit/docs.abapgit.org/pull/62

**Pull request merged**
