### PR TITLE
added screenshot for the abapgit connection to the version constant

### PR DESCRIPTION
**Pull request by oblomov-dev**

### CODE REVIEW

**Comment by mbtools** [comment]
Thanks! The image needs to go in src/.vuepress/public/img/ and linked to with /img/filename.png please  🙏

**Comment by oblomov-dev** [comment]
ah ok, i tried to fix it, hope this works now.

**Comment by mbtools** [comment]
almost. the image file is missing the `.png` extension:

image

**Comment by oblomov-dev** [comment]
ah, should be fixed now

**Comment by mbtools** [comment]
now i see the image :-)... but the version field is empty. just take a pic of your repo setting and say "Here's what the settings look like for another repo" 😁

**Comment by oblomov-dev** [comment]
yes its not as easy for me as expected but i hope it goes in the right direction :)

**Comment by oblomov-dev** [comment]
ok i am done, you can check again.

**Comment by mbtools** [comment]
hey, we're all learning... I'm deep into react which i knew nothing about not too long ago

**Comment by oblomov-dev** [comment]
yes true, and I am still learning git which I knew nothing about not too long ago :) 
Thanks for merging & the abapgit project!

**Pull request merged**
